include_guard = "mpk_ffi_h"
autogen_warning = "/* DO NOT TOUCH */"
include_version = true
language = "C"
cpp_compat = true
line_length = 88

[parse]
parse_deps = true
include = ["mpk_config", "mpk_hash"]
extra_bindings = ["mpk_hash", "mpk_config"]
