[package]
name = "mpk_vm"
version = "0.1.0"
edition = "2021"

[dependencies]
atomic = "0.5"
memmap2 = "0.5"
libc = "0.2"
time = "0.3"
parking_lot = "0.12"
once_cell = "1.10"
vec_map = "0.8"
mpk_hash = { path = "../mpk_hash" }
mpk_parser = { path = "../mpk_parser" }