[package]
name = "mpk_db"
version = "0.1.0"
edition = "2021"

[dependencies]
mpk_id3 = { path = "../mpk_id3" }
mpk_config = { path = "../mpk_config" }
rusqlite = { version = "0.26", features = ["blob", "trace", "uuid", "hooks", "chrono", "unlock_notify"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"