[package]
name = "mpk_db"
version = "0.1.0"
edition = "2021"

[dependencies]
mpk_config = { path = "../mpk_config" }
mpk_hash = { path = "../mpk_hash" }
rusqlite = { version = "0.26", features = ["blob", "trace", "uuid", "hooks", "chrono", "backup"] }
uuid = "0.8"
chrono = "0.4"