[package]
name = "mpk_db"
version = "0.1.0"
edition = "2021"

[dependencies]
mpk_config = { path = "../mpk_config" }
rusqlite = { version = "0.26", features = ["blob", "trace", "uuid", "hooks", "chrono"] }
uuid = "0.8"