[workspace]
members = [
  "src/mpk",
  "src/mpk_gear",
  "src/mpk_config",
  "src/mpk_audio",
  "src/mpk_jack",
  "src/mpk_flate",
  "src/mpk_midi",
  "src/mpk_codec",
  "src/mpk_db",
  "src/mpk_plot",
  "src/mpk_sesh",
  "src/mpk_ffi",
  "src/mpk_http",
  "src/mpk_osc",
]

exclude = [ "vendor/" ]