[package]
name = "ot"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
hound = "3.4"

[[example]]
name = "sample_chain"

[[example]]
name = "track_prep"

[[example]]
name = "decode"