[package]
name = "mpk_codec"
version = "0.1.0"
edition = "2021"

[features]
default = ["snd", "ffmpeg"]
snd = ["sndfile"]
ffmpeg = ["ffmpeg-next"]

[dependencies]
sndfile = { version = "0.1", optional = true}
ffmpeg-next = { version = "5", features = ["codec", "format"], optional = true }