[package]
name = "mpk_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
pest = "2.0"
pest_derive = "2.0"
mpk_gc = { path = "../mpk_gc" }
gc = "0.4"
# phf = { version = "0.10", features = ["macros"] }
chrono = "0.4"