[package]
name = "mpk_repl"
version = "0.1.0"
edition = "2021"

[dependencies]
rustyline = { git = "https://github.com/kkawakam/rustyline" }
rustyline-derive = "0.6"
mpk_config = { path = "../mpk_config" }
mpk_sesh = { path = "../mpk_sesh" }
mpk_db = { path = "../mpk_db" }