use std::str::FromStr;
use crate::ast::Op;
use lalrpop_util::ParseError as PErr;
use crate::ParserError as Err;

grammar;

extern {
  type Error = Err;
}

pub Term: i64 = {
  <n:Num> => n,
  "(" <t:Term> ")" => t,
};

Num: i64 = r"[0-9]+" =>? i64::from_str(<>).map_err(|_| PErr::User { error:  Err::BadNumber });

pub Op: Op = {
  "+" => Op::Add,
  "-" => Op::Sub,
  "*" => Op::Mul,
  "=" => Op::Eq,
  "<" => Op::Lt,
  ">" => Op::Gt,
};