[package]
name = "mdb"
version = "0.1.0"
edition = "2021"

[dependencies]
mpk_id3 = { path = "../mpk_id3" }
mpk_config = { path = "../mpk_config" }
rusqlite = "0.26"
clap = { version = "3.0", features = ["derive"] }
thiserror = "1.0"