#+TITLE: mpk
#+DATE: 2022-05-26
#+AUTHOR: ellis
#+EMAIL: ellis@rwest.io
#+DESCRIPTION: Media Programming Kit
#+OPTIONS: ^:{} e:t f:t timestamp:t toc:nil

=mpk= is a /Media Programming Kit/ -- a development kit for digital
media, taking lessons learned from software engineering and applying
them to creative pursuits. It is a flexible ecosystem designed to
organize my workflow involving hardware, software, and data.

This application is intended for artists, hackers, and
composers. Batteries are not included.

- Status :: =ALPHA= \\
  This project is in alpha and will only deal with audio for quite
  some time since that's the medium I'm most interested in. There are
  future plans for image/video/text support.
  
  
#+TOC: headlines 2

* Features

* Usage
MPK is meant to be used on a Linux box. In this example we'll be using
Arch Linux.

MPK also runs on MacOS but some of the project management
functionality isn't available. Most notably, you can't run the [[https://new-session-manager.jackaudio.org][NSM]]
server on MacOS, but you can still interact with one remotely. All
other features are supported on both platforms.
* Installation
First install the dependencies:
#+begin_src shell
  # install rustup
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
  rustup default nightly

  # for processing analysis files
  curl https://essentia.upf.edu/extractors/essentia-extractors-v2.1_beta2-linux-x86_64.tar.gz -o essentia-extractors.tar.gz
  tar -xf essentia-extractors.tar.gz essentia-extractors-v2.1_beta2/{streaming_extractor_freesound,streaming_extractor_music}
  mv essentia-extractors-v2.1_beta2/{streaming_extractor_freesound,streaming_extractor_music} /usr/local/bin/ && rm -r essentia-extractors-v2.1_beta2

  sudo pacman -S nim alsa-lib jack2 ffmpeg new-session-manager supercollider
#+end_src


It is recommended to install [[https://nim-lang.org/][Nim]] so that you can run the build scripts
in =config.nims=.

Simply run =nim install= in the project root to install the mpk
binaries in =~/.cargo=.

Run =nim help= to see the other commands and flags available.

* Initialization
Once the binary is installed run =mpk init= to initialize the app
directories at =~/mpk= as well as the database and TOML config file.

#+begin_src shell :exports results :results code
ls ~/mpk
#+end_src
#+RESULTS:
#+begin_src shell
mpk.toml
db
analysis
patches
plugins
sesh
samples
tracks
#+end_src
* Configuration
The default =mpk.toml= config file looks like this:
#+begin_src conf-toml
[fs]
root = '~/mpk'

[db]
path = '~/mpk/db'
mode = 'Fast'
cache_capacity = 1073741824
print_on_drop = false
use_compression = false
compression_factor = 5

[jack]
name = 'mpk'
audio = 'alsa'
midi = 'seq'
device = 'default'
realtime = true
autoconnect = ' '
temp = false
rate = 44100
period = 1024
n_periods = 2

[metro]
bpm = 120
time_sig = [
    4,
    4,
]

[sesh]
client_addr = '127.0.0.1:0'

[net]
socket = '127.0.0.1:0'

[engine]
socket = '127.0.0.1:0'

[gear]
#+end_src
Much of the configuration can be overridden by CLI flags but you may
want to change some of the default values. Some of the optional
settings aren't included in the default file:
- fs.{=ext_samples=, =ext_tracks=, =ext_projects=, =ext_plugins=, =ext_patches=}
- gear.{=octatrack=, =analog_rytm=, =op_1=}
- metro.{=tic=, =toc=}
- net.{=freesound=, =musicbrainz=, =youtube=, =spotify=}.{=client_id=, =client_secret=, =redirect_url=}
* Dev Dependencies
=*= := /use your OS package manager (apt, brew, pacman, etc)/
- [[https://www.rust-lang.org/tools/install][Rust]] :: install with [[https://rustup.rs/][rustup.rs]]
- C Compiler :: [[https://gcc.gnu.org/][GCC]] or [[https://llvm.org/][LLVM]] *
- [[https://nim-lang.org/][Nim]] :: *
  - used as a build tool via [[https://nim-lang.org/docs/nims.html][NimScript]].
- [[https://jackaudio.org/][JACK]] :: *
- [[https://new-session-manager.jackaudio.org][NSM]] :: *
- [[https://valgrind.org/][Valgrind]] :: *
  - used to detect issues with FFI memory management.
