[package]
name = "mpk_ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type =["cdylib", "staticlib"]

[dependencies]
libc = "0.2"
mpk_id3 = { path = "../mpk_id3" }
mpk_db = { path = "../mpk_db" }

[build-dependencies]
cbindgen = "0.20"