include_guard = "mpk_ffi_h"
autogen_warning = "/* DO NOT TOUCH */"
include_version = true
language = "C"
cpp_compat = true
[parse]
parse_deps = true
include = ["mpk_db", "mpk_id3", "mpk_config", "mpk_sesh", "mpk_jack", "mpk_dsp", "mpk_midi", "mpk_gear", "mpk_flate"]
